name: Build
on: [push]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get Go version from go.mod
        run: echo "GO_MOD_VERSION=$(grep "go 1." go.mod | cut -d " " -f 2)" >> $GITHUB_ENV
      - name: Update Vars
        id: vars
        run: |
          echo ::set-output name=go_latest_version::$(curl -s https://raw.githubusercontent.com/actions/go-versions/main/versions-manifest.json | grep -oE '"version": "[0-9]{1}.[0-9]{1,}(.[0-9]{1,})?"' | grep  ${{ env.GO_MOD_VERSION }} | head -1 | cut -d':' -f2 | sed 's/ //g; s/"//g')
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ steps.vars.outputs.go_latest_version }}
      - name: Test
        run: go test -v .
      - name: Build
        run: go build -v .
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}